import Link from "next/link";
import { BadgeCheck, CheckCircle2, Database, DoorOpen, KeyRound, Languages, ShieldCheck, Timer } from "lucide-react";
import { demoAccounts, roleLabels } from "@/lib/demo-accounts";
import { getLocale } from "@/lib/demo-session";
import { pick } from "@/lib/i18n";

export default async function AppInfoPage() {
  const locale = await getLocale();
  const ar = locale === "ar";
  const cycle = ar
    ? ["البحث والفلترة", "اختيار وحدة ومساحة", "تسجيل الدخول", "تأكيد حجز ديمو", "ظهور الإقامة والدفعات في مسكني", "إرسال طلب صيانة", "متابعة الحجز والطلب من التشغيل"]
    : ["Search and filter", "Choose a property and space", "Sign in", "Confirm a demo booking", "See stay and payments in My Maskan", "Submit maintenance", "Review booking and request in operations"];

  return (
    <main className="shell py-8 md:py-12">
      <div className="max-w-3xl"><p className="eyebrow">{pick(locale, "معلومات التطبيق", "Application information")}</p><h1 className="mt-2 text-3xl font-bold md:text-4xl">{pick(locale, "نسخة مسكن التجريبية", "Maskan demonstration build")}</h1><p className="mt-4 leading-7 text-[var(--muted)]">{pick(locale, "النسخة دي معمولة لعرض دورة العميل والتشغيل كاملة ببيانات وحسابات وهمية. لا يوجد دفع حقيقي أو عقد قانوني أو بيانات تشغيل فعلية.", "This build demonstrates the complete resident and operations cycle with dummy accounts and data. It does not process real payments, legal contracts, or live operations.")}</p></div>

      <section className="mt-8"><p className="eyebrow">{pick(locale, "وعد مسكن", "The Maskan promise")}</p><h2 className="mt-2 text-2xl font-bold">{pick(locale, "سرعة · ثقة · أمان", "Speed · Trust · Safety")}</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="surface p-5"><Timer className="size-5 text-[var(--brand)]" /><h3 className="mt-4 font-bold">{pick(locale, "سرعة", "Speed")}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{pick(locale, "من التسجيل والبحث لحد الحجز والاستلام بأقل خطوات ممكنة.", "From registration and search through booking and move-in, with as few steps as possible.")}</p></div><div className="surface p-5"><BadgeCheck className="size-5 text-[var(--brand)]" /><h3 className="mt-4 font-bold">{pick(locale, "ثقة", "Trust")}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{pick(locale, "السعر والوديعة والخدمات واضحين، وفريق مسكن مسؤول عن التجربة كاملة.", "Pricing, deposits, and services are clear, with one Maskan team accountable throughout.")}</p></div><div className="surface p-5"><ShieldCheck className="size-5 text-[var(--brand)]" /><h3 className="mt-4 font-bold">{pick(locale, "أمان", "Safety")}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{pick(locale, "الهوية والعقد والدفعات والطلبات موثّقة ومحفوظة.", "Identity, contracts, payments, and requests are documented and protected.")}</p></div></div></section>

      <section className="mt-8 flex items-start gap-4 border-y border-[var(--line)] py-6"><DoorOpen className="mt-1 size-6 shrink-0 text-[var(--brand)]" /><div><h2 className="font-bold">{pick(locale, "نوع السكن في النموذج الحالي", "Current housing offer")}</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{pick(locale, "مسكن يقدم سكنًا مشتركًا بغرف خاصة أو مشتركة، ويقدم أيضًا شققًا كاملة لأسرة واحدة. سعر السكن المشترك يبدأ من سعر الفرد أو المساحة، بينما سعر شقة الأسرة هو سعر الوحدة بالكامل بعقد واحد.", "Maskan offers shared housing through private and shared rooms, alongside complete apartments for one family. Shared-housing rates start per resident or space, while a family-apartment rate covers the whole unit under one contract.")}</p><p className="mt-2 text-xs text-[var(--muted)]">{pick(locale, "الداتا الحالية للقاهرة الكبرى كبداية تشغيلية، والتوسع المستهدف يشمل مصر كلها.", "Current demo data is limited to Greater Cairo as an operating start, with nationwide expansion remaining the target.")}</p></div></section>

      <section className="mt-8 grid gap-4 md:grid-cols-3"><div className="surface p-5"><Languages className="size-5 text-[var(--brand)]" /><h2 className="mt-4 font-bold">{pick(locale, "اللغة والتصميم", "Language and interface")}</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{pick(locale, "العربية المصرية بخط Cairo هي الافتراضية، واللغة محفوظة في جلسة الحساب. الحقول والقوائم متاحة بلوحة المفاتيح، وشريط البحث يدعم مسح المنطقة والتاريخ والمدة بضغطة واحدة.", "Egyptian Arabic set in Cairo is the default and the language is stored in the account session. Controls are keyboard accessible, and the home search clears area, date, and stay length in one action.")}</p></div><div className="surface p-5"><ShieldCheck className="size-5 text-[var(--brand)]" /><h2 className="mt-4 font-bold">{pick(locale, "الجلسة والصلاحيات", "Session and permissions")}</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{pick(locale, "الجلسات موقعة وHTTP-only، وكل دور يفتح الشاشات والنطاق المسموح له داخل الديمو.", "Sessions are signed and HTTP-only. Each role opens only its permitted demo screens and scope.")}</p></div><div className="surface p-5"><Database className="size-5 text-[var(--brand)]" /><h2 className="mt-4 font-bold">{pick(locale, "حدود الديمو", "Demo boundary")}</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{pick(locale, "الحالة محفوظة في Cookies وليست Supabase. مرحلة الإنتاج تستبدلها بـAuth وPostgres وRLS وStorage.", "State is stored in cookies, not Supabase. Production replaces it with Auth, Postgres, RLS, and Storage.")}</p></div></section>

      <section className="mt-10"><p className="eyebrow">{pick(locale, "الدورة المقفولة", "Closed demo cycle")}</p><h2 className="mt-2 text-2xl font-bold">{pick(locale, "من البحث لحد التشغيل", "From discovery through operations")}</h2><ol className="mt-5 grid gap-2 sm:grid-cols-2">{cycle.map((item, index) => <li key={item} className="surface flex items-center gap-3 p-4"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-[var(--brand)] text-xs font-bold text-white">{index + 1}</span><span className="text-sm font-bold">{item}</span></li>)}</ol></section>

      <section className="mt-10"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="eyebrow">{pick(locale, "حسابات جاهزة", "Ready accounts")}</p><h2 className="mt-2 text-2xl font-bold">{pick(locale, "كل أدوار التطبيق", "Every application role")}</h2></div><Link href="/login" className="button-primary"><KeyRound className="size-4" />{pick(locale, "افتح صفحة الدخول", "Open sign in")}</Link></div><div className="mt-5 overflow-x-auto rounded-lg border border-[var(--line)] bg-white"><table className="w-full min-w-[760px] text-start text-sm"><thead className="bg-[#f3f5f2] text-xs text-[var(--muted)]"><tr><th className="px-4 py-3">{pick(locale, "الدور", "Role")}</th><th className="px-4 py-3">{pick(locale, "الاسم", "Name")}</th><th className="px-4 py-3">{pick(locale, "البريد", "Email")}</th><th className="px-4 py-3">{pick(locale, "كلمة المرور", "Password")}</th><th className="px-4 py-3">{pick(locale, "اللغة", "Language")}</th></tr></thead><tbody className="divide-y divide-[var(--line)]">{demoAccounts.map((account) => <tr key={account.id}><td className="px-4 py-4 font-bold">{account.isUnitRepresentative ? pick(locale, "ممثل وحدة", "Unit representative") : roleLabels[account.role][locale]}</td><td className="px-4 py-4">{ar ? account.fullNameAr : account.fullName}</td><td className="px-4 py-4" dir="ltr"><code>{account.email}</code></td><td className="px-4 py-4" dir="ltr"><code>{account.password}</code></td><td className="px-4 py-4">{account.preferredLanguage === "ar" ? "العربية" : "English"}</td></tr>)}</tbody></table></div></section>

      <section className="mt-10 rounded-lg bg-[var(--brand-dark)] p-6 text-white"><div className="flex items-start gap-4"><CheckCircle2 className="mt-1 size-6 shrink-0 text-[var(--accent)]" /><div><h2 className="text-xl font-bold">{pick(locale, "ما تم تنفيذه وما لم يتم", "What is and is not implemented")}</h2><p className="mt-2 text-sm leading-7 text-white/70">{pick(locale, "الدخول والصلاحيات والبروفايل واللغة ومعرض الصور والحجز والصيانة مترابطين داخل دورة الديمو. الشات العائم يقدم دعمًا خاصًا وشاتًا لسكان الوحدة مع صور وفيديوهات محمية ومتحقق منها، والكاميرات مدمجة داخل الإقامة ولوحة التشغيل حسب الدور والنطاق. البث الحقيقي وسجل الوصول وقاعدة رسائل دائمة وفحص المرفقات ضد البرمجيات الضارة والإشراف على المحتوى والدفع ما زال يحتاج بنية إنتاج مؤمّنة.", "Sign-in, roles, profiles, language, the image gallery, booking, and maintenance are connected inside the demo cycle. The floating chat provides private support and same-unit conversations with validated, protected image and video attachments; cameras are embedded in the stay and operations dashboard according to role and scope. Real streams, access auditing, persistent messaging, malware scanning, moderation, and payments still require secured production infrastructure.")}</p></div></div></section>
    </main>
  );
}
